apiVersion: apps/v1
kind: Deployment
metadata:
  name: markethub-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: markethub
  template:
    metadata:
      labels:
        app: markethub
    spec:
      containers:
        - name: markethub
          image: vansh1999/markethub:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: markethub-service
spec:
  selector:
    app: markethub
  ports:
    - protocol: TCP
      port: 80   # External port exposed for accessing the app
      targetPort: 8000  # Port your Django app listens on inside the container
  type: LoadBalancer  # Use LoadBalancer to expose the app externally

