# Generated by Django 4.2.16 on 2024-09-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=400)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
